### ISSUE TITLE
%{in} not using just base name

### ISSUE THREAD

**Issue by nick-youngblut** [zjshi/gt-pro#36]
The `gt_pro` help docs state:

>  %{in} expands to the corresponding input base name

...but the **base name** is not used. Instead the entire input file path is used. For instance, if I provide `-o /path/to/gt-pro/output/%{in} /path/to/input/reads.fq`, then the output is written to `/path/to/gt-pro/output/path_to_input_reads.tsv`. In other words, `gt_pro` is using the entire input file path for `%{in}` and just converting the `/` characters to `_`, instead of just using the basename (eg., `reads.fq`).

**Comment by zjshi** [comment]
Yes, this can be achieved using the -C flag. Let me know please if you have any issues getting it work.
