### ISSUE TITLE
verify if specific SNP/gene is in database

### ISSUE THREAD

**Issue by ramiroricardo** [zjshi/gt-pro#39]
Hi all,

How would you search the database to check if specific SNPs/genes are present?

e.g. if one is interested in a specific gene of species X.

Thanks

**Comment by zjshi** [comment]
I apologize for my long delayed response. GT-Pro has been updated frequently until recently. For a specific SNP, one may look it up with the corresponding variant file (VCF format) and reference genome at https://fileshare.czbiohub.org/s/waXQzQ9PRZPwTdk?path=%2Fvariation_in_species. For a specific gene, additional step (gene prediction) may be required before the lookup. It is typically done with programs like Prodigal with reference genome as input. I am closing this issue for now. Feel free to reopen it if you have follow-up questions.
