### ISSUE TITLE
Can't download resources - ERROR 403: Forbidden

### ISSUE THREAD

**Issue by LeCray** [zjshi/gt-pro#40]
Upon trying out the tutorial for the first time, I am stuck on downloading the raw material (the two S3 links).  No matter what I try, either using "aws s3 cp" or "wget", either way returns a 403 forbidden error. Are the resources public or not?

Please advise.

**Comment by zjshi** [comment]
This error is due to a policy change in CZ Biohub which no longer allows sharing files in its AWS S3 bucket with the public. I updated the download links, let me know please if you still have issues accessing these files. Thanks for reporting this issue!
