### ISSUE TITLE
GT-pro build Error : Multispecies kmers present in input

### ISSUE THREAD

**Issue by majunyeong** [zjshi/gt-pro#41]
Hi,

While executing the "GT_Pro build" command,
the following error occurred:

...
Starting to check conflicts:  Will filter out kmers that occur in multiple species.
Filtering done! It took 27 secs.
The filtered kmer list has 939378490 monospecies kmers (572645838 unique).
Purging conflicts removed 48753154 multispecies kmers (9684824 unique).
ERROR:  Multispecies kmers found!   There is possibly a problem with the upstream sckmerdb_allowed.tsv generator.
db_build: ./src/db_build.cpp:538: void multi_btc64(int, const char**): Assertion `false && "multispecies kmers present in input"\' failed.\n/bin/sh: line 1: 3193510 Aborted
...

How can I solve this error?
What's wrong with my input?

**Comment by zjshi** [comment]
Hi,

It is seemingly due to the non-unique kmers were found even after unique screening. To shoot this issue, would you please give a more details about what you did here? It will be super helpful if you could give some step-wise description.

**Comment by zjshi** [comment]
I will close this issue for now but please feel free to reopen it.

**Comment by zjshi** [comment]
Hi majunyeong, another user reported the same issue and led to a bug fix. Hope it helps.
