### ISSUE TITLE
Error writing output xxx_gtpro__20190723_881species.tsv.gz cl 1067

### ISSUE THREAD

**Issue by yejunbin** [zjshi/gt-pro#42]
Error happen after [Stats] 1852819 snps, ...., for xx.fq.gz

"Error writing output xxx_gtpro__20190723_881species.tsv.gz cl 1067"

**Comment by zjshi** [comment]
Thanks for using GT-Pro! Could you please give a bit more details about your running?

**Comment by yejunbin** [comment]
The run command is :

sample="ADBB"
/Disk1/github/gt-pro/GT_Pro genotype -d /Disk2/database/GT-pro/20190723_881species -o ${sample}_gt_pro \
		data/${sample}/${sample}.R1.clear.fastq.gz \
		data/${sample}/${sample}.R2.clear.fastq.gz 	

The Log:

gt_pro	/Disk2/database/GT-pro/20190723_881species	28	no_overwrite
1642347102634:  [Info] Starting to load DB: /Disk2/database/GT-pro/20190723_881species
1642347102634:  [Info] MMAPPING /Disk2/database/GT-pro/20190723_881species_optimized_db_snps.bin
1642347102737:  [Info] MMAPPING /Disk2/database/GT-pro/20190723_881species_optimized_db_kmer_index.bin
1642347103076:  [Info] Using -l 32 -m 36 as optimal for system RAM
1642347103076:  [Info] MMAPPING /Disk2/database/GT-pro/20190723_881species_optimized_db_mmer_bloom_36.bin
1642347103321:  [Info] MMAPPING /Disk2/database/GT-pro/20190723_881species_optimized_db_lmer_index_32.bin
1642347104626:  [Info] Done with init for optimized DB with 2856121626 kmers.  That took 1 seconds.
1642347104761:  [Info] Waiting for all readers to quiesce
1642347107396:  [Progress] 1.01 million reads scanned after 2 seconds, and 0 files output.
1642347108599:  [Progress] 2.03 million reads scanned after 3 seconds, and 0 files output.
1642347109894:  [Progress] 3.17 million reads scanned after 5 seconds, and 0 files output.
1642347111184:  [Progress] 4.24 million reads scanned after 6 seconds, and 0 files output.
1642347112662:  [Progress] 5.26 million reads scanned after 8 seconds, and 0 files output.
1642347113908:  [Progress] 6.29 million reads scanned after 9 seconds, and 0 files output.
1642347115251:  [Progress] 7.31 million reads scanned after 10 seconds, and 0 files output.
1642347116372:  [Progress] 8.33 million reads scanned after 11 seconds, and 0 files output.
1642347117515:  [Progress] 9.35 million reads scanned after 12 seconds, and 0 files output.
1642347118709:  [Progress] 10.38 million reads scanned after 14 seconds, and 0 files output.
1642347119837:  [Progress] 11.4 million reads scanned after 15 seconds, and 0 files output.
1642347121145:  [Progress] 12.42 million reads scanned after 16 seconds, and 0 files output.
1642347122374:  [Progress] 13.47 million reads scanned after 17 seconds, and 0 files output.
1642347123467:  [Progress] 14.5 million reads scanned after 18 seconds, and 0 files output.
1642347124519:  [Progress] 15.52 million reads scanned after 19 seconds, and 0 files output.
1642347125633:  [Progress] 16.58 million reads scanned after 21 seconds, and 0 files output.
1642347127070:  [Progress] 17.68 million reads scanned after 22 seconds, and 0 files output.
1642347128267:  [Progress] 18.78 million reads scanned after 23 seconds, and 0 files output.
1642347129438:  [Progress] 19.84 million reads scanned after 24 seconds, and 0 files output.
1642347131202:  [Progress] 20.94 million reads scanned after 26 seconds, and 0 files output.
1642347132399:  [Progress] 21.96 million reads scanned after 27 seconds, and 0 files output.
1642347133597:  [Progress] 23.09 million reads scanned after 28 seconds, and 0 files output.
1642347134802:  [Progress] 24.11 million reads scanned after 30 seconds, and 0 files output.
1642347135952:  [Progress] 25.13 million reads scanned after 31 seconds, and 0 files output.
1642347136942:  [Progress] 26.15 million reads scanned after 32 seconds, and 0 files output.
1642347138106:  [Progress] 27.2 million reads scanned after 33 seconds, and 0 files output.
1642347139239:  [Progress] 28.26 million reads scanned after 34 seconds, and 0 files output.
1642347140744:  [Progress] 29.31 million reads scanned after 36 seconds, and 0 files output.
1642347141948:  [Progress] 30.33 million reads scanned after 37 seconds, and 0 files output.
1642347143112:  [Progress] 31.39 million reads scanned after 38 seconds, and 0 files output.
1642347144470:  [Progress] 32.41 million reads scanned after 39 seconds, and 0 files output.
1642347146005:  [Progress] 33.41 million reads scanned after 41 seconds, and 0 files output.
1642347147062:  [Progress] 34.43 million reads scanned after 42 seconds, and 0 files output.
1642347148293:  [Progress] 35.44 million reads scanned after 43 seconds, and 0 files output.
1642347149427:  [Progress] 36.46 million reads scanned after 44 seconds, and 0 files output.
1642347150608:  [Progress] 37.52 million reads scanned after 45 seconds, and 0 files output.
1642347152056:  [Progress] 38.57 million reads scanned after 47 seconds, and 0 files output.
1642347153604:  [Progress] 39.59 million reads scanned after 48 seconds, and 0 files output.
1642347154743:  [Progress] 40.61 million reads scanned after 50 seconds, and 0 files output.
1642347155900:  [Progress] 41.67 million reads scanned after 51 seconds, and 0 files output.
1642347157243:  [Progress] 42.68 million reads scanned after 52 seconds, and 0 files output.
1642347158557:  [Progress] 43.69 million reads scanned after 53 seconds, and 0 files output.
1642347160283:  [Progress] 44.71 million reads scanned after 55 seconds, and 0 files output.
1642347161362:  [Progress] 45.73 million reads scanned after 56 seconds, and 0 files output.
1642347162582:  [Progress] 46.83 million reads scanned after 57 seconds, and 0 files output.
1642347164222:  [Progress] 47.85 million reads scanned after 59 seconds, and 0 files output.
1642347165307:  [Progress] 48.87 million reads scanned after 60 seconds, and 0 files output.
1642347166470:  [Progress] 49.91 million reads scanned after 61 seconds, and 0 files output.
1642347167584:  [Progress] 50.98 million reads scanned after 62 seconds, and 0 files output.
1642347168750:  [Progress] 52 million reads scanned after 64 seconds, and 0 files output.
1642347169955:  [Progress] 53.06 million reads scanned after 65 seconds, and 0 files output.
1642347171398:  [Progress] 54.08 million reads scanned after 66 seconds, and 0 files output.
1642347172546:  [Progress] 55.14 million reads scanned after 67 seconds, and 0 files output.
1642347173675:  [Progress] 56.18 million reads scanned after 69 seconds, and 0 files output.
1642347175175:  [Progress] 57.21 million reads scanned after 70 seconds, and 0 files output.
1642347176688:  [Progress] 58.22 million reads scanned after 72 seconds, and 0 files output.
1642347177775:  [Progress] 59.27 million reads scanned after 73 seconds, and 0 files output.
1642347179136:  [Progress] 60.28 million reads scanned after 74 seconds, and 0 files output.
1642347180652:  [Progress] 61.36 million reads scanned after 76 seconds, and 0 files output.
1642347181790:  [Progress] 62.4 million reads scanned after 77 seconds, and 0 files output.
1642347183180:  [Progress] 63.4 million reads scanned after 78 seconds, and 0 files output.
1642347184521:  [Progress] 64.41 million reads scanned after 79 seconds, and 0 files output.
1642347185613:  [Progress] 65.41 million reads scanned after 80 seconds, and 0 files output.
1642347186865:  [Progress] 66.46 million reads scanned after 82 seconds, and 0 files output.
1642347188019:  [Progress] 67.47 million reads scanned after 83 seconds, and 0 files output.
1642347189384:  [Progress] 68.5 million reads scanned after 84 seconds, and 0 files output.
1642347190751:  [Progress] 69.54 million reads scanned after 86 seconds, and 0 files output.
1642347192128:  [Progress] 70.62 million reads scanned after 87 seconds, and 0 files output.
1642347193451:  [Progress] 71.66 million reads scanned after 88 seconds, and 0 files output.
1642347194771:  [Progress] 72.74 million reads scanned after 90 seconds, and 0 files output.
1642347196278:  [Progress] 73.81 million reads scanned after 91 seconds, and 0 files output.
1642347197449:  [Progress] 74.86 million reads scanned after 92 seconds, and 0 files output.
1642347198891:  [Progress] 75.95 million reads scanned after 94 seconds, and 0 files output.
1642347200245:  [Progress] 76.99 million reads scanned after 95 seconds, and 0 files output.
1642347201878:  [Progress] 78.05 million reads scanned after 97 seconds, and 0 files output.
1642347203242:  [Progress] 79.06 million reads scanned after 98 seconds, and 0 files output.
1642347204275:  [Progress] 80.06 million reads scanned after 99 seconds, and 0 files output.
1642347205769:  [Progress] 81.1 million reads scanned after 101 seconds, and 0 files output.
1642347207249:  [Progress] 82.17 million reads scanned after 102 seconds, and 0 files output.
1642347208438:  [Progress] 83.2 million reads scanned after 103 seconds, and 0 files output.
1642347209764:  [Progress] 84.25 million reads scanned after 105 seconds, and 0 files output.
1642347210931:  [Progress] 85.29 million reads scanned after 106 seconds, and 0 files output.
1642347212059:  [Progress] 86.33 million reads scanned after 107 seconds, and 0 files output.
1642347213184:  [Progress] 87.33 million reads scanned after 108 seconds, and 0 files output.
1642347214549:  [Progress] 88.34 million reads scanned after 109 seconds, and 0 files output.
1642347215815:  [Progress] 89.38 million reads scanned after 111 seconds, and 0 files output.
1642347217140:  [Progress] 90.41 million reads scanned after 112 seconds, and 0 files output.
1642347218454:  [Progress] 91.45 million reads scanned after 113 seconds, and 0 files output.
1642347219994:  [Progress] 92.53 million reads scanned after 115 seconds, and 0 files output.
1642347221168:  [Progress] 93.53 million reads scanned after 116 seconds, and 0 files output.
1642347222669:  [Progress] 94.54 million reads scanned after 118 seconds, and 0 files output.
1642347224379:  [Progress] 95.62 million reads scanned after 119 seconds, and 0 files output.
1642347225878:  [Progress] 96.62 million reads scanned after 121 seconds, and 0 files output.
1642347226978:  [Progress] 97.63 million reads scanned after 122 seconds, and 0 files output.
1642347228126:  [Progress] 98.66 million reads scanned after 123 seconds, and 0 files output.
1642347229519:  [Progress] 99.71 million reads scanned after 124 seconds, and 0 files output.
1642347230741:  [Progress] 100.72 million reads scanned after 126 seconds, and 0 files output.
1642347231782:  [Progress] 101.8 million reads scanned after 127 seconds, and 0 files output.
1642347232973:  [Progress] 102.86 million reads scanned after 128 seconds, and 0 files output.
1642347234564:  [Progress] 103.86 million reads scanned after 129 seconds, and 0 files output.
1642347235712:  [Progress] 104.9 million reads scanned after 131 seconds, and 0 files output.
1642347237107:  [Progress] 105.9 million reads scanned after 132 seconds, and 0 files output.
1642347238325:  [Progress] 106.93 million reads scanned after 133 seconds, and 0 files output.
1642347239984:  [Progress] 107.97 million reads scanned after 135 seconds, and 0 files output.
1642347241856:  [Progress] 108.99 million reads scanned after 137 seconds, and 0 files output.
1642347243354:  [Progress] 110.01 million reads scanned after 138 seconds, and 0 files output.
1642347243712:  [Done] searching is completed for the 56356227 reads input from data/F1T2R/F1T2R.R2.clear.fastq.gz
1642347245166:  [Progress] 111.04 million reads scanned after 140 seconds, and 0 files output.
1642347246367:  [Stats] 1419993 snps, 56356227 reads, 30.86 hits/snp, for data/F1T2R/F1T2R.R2.clear.fastq.gz
1642347246373:  [ERROR] Error writing output F1T2R_gt_pro.tsv.gz cl 1067
1642347247479:  [Progress] 112.71 million reads scanned after 142 seconds, and 1 files output.
1642347247479:  [Done] searching is completed for the 56356227 reads input from data/F1T2R/F1T2R.R1.clear.fastq.gz
1642347249807:  [Stats] 1466355 snps, 56356227 reads, 32.43 hits/snp, for data/F1T2R/F1T2R.R1.clear.fastq.gz
1642347249818:  [ERROR] Error writing output F1T2R_gt_pro.tsv.gz cl 1067
1642347249865:  112.71 million reads were scanned after 145 seconds
*** Failed for ALL 2 input files. ***

-------------

Some of my samples can get  successful results.

**Comment by yejunbin** [comment]
some samples which get error above can get results after rerunning, but not all of them, many still get errors.

**Comment by zjshi** [comment]
It could be due to the dependency issues related to writing in compressed format. Would you please try running the program on the uncompressed problematic input files. In your example, gunzip both ADBB.R1.clear.fastq.gz and ADBB.R2.clear.fastq.gz first, then run GT_Pro on ADBB.R1.clear.fastq and ADBB.R2.clear.fastq. Let me know please if this error persists. Thanks!

**Comment by zjshi** [comment]
Please see this issue for a possible solution: https://github.com/zjshi/gt-pro/issues/44
