### ISSUE TITLE
GT-pro optimize issues

### ISSUE THREAD

**Issue by wangbaikui** [zjshi/gt-pro#45]
GT-pro version: 1.0.1
python version: 3.9.10

Hi guys,
When running "./GT-pro optimise" with example fastq file "/path/to/gt-pro/test/SRR413665_2.fastq.gz", program returned those error messages as below:
/home/data/t010209/gt-pro/GT_Pro optimize --db /home/data/t010209/gt-pro/20190723_881species --in /home/data/t010209/gt-pro/test/SRR413665_2.fastq.gz

[OK] start initial optimization
Traceback (most recent call last):
  File "/home/data/t010209/gt-pro/scripts/optimize.py", line 99, in <module>
    main()
  File "/home/data/t010209/gt-pro/scripts/optimize.py", line 94, in main
    optimize(dbname)
  File "/home/data/t010209/gt-pro/scripts/optimize.py", line 61, in optimize
    assert False
AssertionError

Do you have any ideas about this issue?

In addition, is there a docker-image of GT-Pro? It will be helpful for the user like me has a brand new install of CentOS/Ubuntu and for the users to avoid the dependencies issues of GT-Pro installation.
to avoid 

Many thanks!

**Comment by zjshi** [comment]
hi wangbaikui, thanks for trying GT-Pro! The main program appears to complain about the missing physical file of the database. Could you please make sure both 20190723_881species_optimized_db_kmer_index.bin and  20190723_881species_optimized_db_snps.bin are in place?

**Comment by zjshi** [comment]
Is there a specific dependency issue you are experiencing? Although we would like to have it, we currently don't have a docker image.

**Comment by wangbaikui** [comment]
> hi wangbaikui, thanks for trying GT-Pro! The main program appears to complain about the missing physical file of the database. Could you please make sure both 20190723_881species_optimized_db_kmer_index.bin and 20190723_881species_optimized_db_snps.bin are in place?

![image](https://user-images.githubusercontent.com/42957791/152484010-6a62df48-38fe-49da-a2a1-8f802bfbc016.png)

**Comment by wangbaikui** [comment]
> hi wangbaikui, thanks for trying GT-Pro! The main program appears to complain about the missing physical file of the database. Could you please make sure both 20190723_881species_optimized_db_kmer_index.bin and 20190723_881species_optimized_db_snps.bin are in place?

> Hi，Shi, thanks for the reply!
I downloaded the two default database files using the recommended ways "wget --content-disposition" and put they into the folder of "20190723_881species":
![image](https://user-images.githubusercontent.com/42957791/152485709-5c76b413-781a-4c1b-85cb-3c366f2af0d8.png)

where the gt-pro install is:
![image](https://user-images.githubusercontent.com/42957791/152487163-dac880a0-968f-4dc3-aff5-3c0528241d99.png)

I run the following command with full path in a in a new environment and still received the same issue:
/home/data/t0202014/tools/gt-pro/GT_Pro optimize --db /home/data/t0202014/database/20190723_881species --in /home/data/t0202014/tools/gt-pro/test/SRR413665_2.fastq.gz
[OK] start initial optimization
Traceback (most recent call last):
  File "/home/data/t0202014/tools/gt-pro/scripts/optimize.py", line 99, in <module>
    main()
  File "/home/data/t0202014/tools/gt-pro/scripts/optimize.py", line 94, in main
    optimize(dbname)
  File "/home/data/t0202014/tools/gt-pro/scripts/optimize.py", line 61, in optimize
    assert False
AssertionError

BY the way, I have no root authorization of the computing server, is this related to the above mentioned issue?

**Comment by zjshi** [comment]
This is very helpful! My hunch is that it was caused by the missing parent folder which happens to have the same name as the database. Would you please try the following command line to see if the problem still there?

`/home/data/t0202014/tools/gt-pro/GT_Pro optimize --db /home/data/t0202014/database/20190723_881species/20190723_881species --in /home/data/t0202014/tools/gt-pro/test/SRR413665_2.fastq.gz`

**Comment by wangbaikui** [comment]
> This is very helpful! My hunch is that it was caused by the missing parent folder which happens to have the same name as the database. Would you please try the following command line to see if the problem still there?
/home/data/t0202014/tools/gt-pro/GT_Pro optimize --db /home/data/t0202014/database/20190723_881species/20190723_881species --in /home/data/t0202014/tools/gt-pro/test/SRR413665_2.fastq.gz`

> Very greatfull! It worked very well accroding to your suggestion! And there is no other errors occured when i run  the “Step-by-step Tutorial”!
With misunderstanding the sentence "The name of this default database is "20190723_881species".", I created a new folder named "20190723_881species" and put the two downloaded default database files into the new folder.
Thanks so much!

**Comment by wangbaikui** [comment]
> Is there a specific dependency issue you are experiencing? Although we would like to have it, we currently don't have a docker image.

> Most dependency issues are the uninstalled python packages and i sovled it. It will be easier for the first-time users to quickly get familiar with GT-Pro with a docker image. Hope for a docker image or a conda installation in the future.

**Comment by wangbaikui** [comment]
> Is there a specific dependency issue you are experiencing? Although we would like to have it, we currently don't have a docker image.

> Most dependency issues are the uninstalled python packages and i sovled it. It will be easier for the first-time users to quickly get familiar with GT-Pro with a docker image. Hope for a docker image or a conda installation in the future.

**Comment by zjshi** [comment]
Great to hear, thanks for trying GT-Pro :)
