### ISSUE TITLE
Error writing file (cl 1067) seems to be result of g++ version

### ISSUE THREAD

**Issue by bsmith89** [zjshi/gt-pro#48]
I was getting the dreaded `[ERROR] Error writing output data/reads/SRR15089604/r2.proc.gtpro_raw.gz.tsv.gz cl 1067` with some of my Docker/Singularity images for GT-Pro but not others.

I seem to have solved the issue by switching from the mambaforge base image `condaforge/mambaforge:4.11.0-4` to `ubuntu:18.04`, suggesting that it may be the g++ version that matters.

```
old-image > g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

new-image > g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

Any idea why?

**Comment by zjshi** [comment]
Hey Byron, thanks for reporting this issue. I have seen other reports on cl 1067 error, which is seemingly HPC and gxx related. I also found using -C flag to specify a writable location could consistently solve the problem on my side. Please see a previous thread for more details: issue #44 . Sorry for missing your comment. Github (or I) messed up my notification for this repo somehow. If I haven't got back to you next time, please pin me at zhoushihn@gmail.com.

**Comment by zjshi** [comment]
Closing it for now, please feel free to reopen it if the problem emerges again.
