### ISSUE TITLE
list dependency versions 

### ISSUE THREAD

**Issue by nick-youngblut** [zjshi/gt-pro#51]
The [Dependencies docs](https://github.com/zjshi/gt-pro#dependencies) do not list the acceptable dependency versions. It would be very beneficial to have a list of versions for each dependency.

**Comment by nick-youngblut** [comment]
It also appears that `g++` is a dependency, but I don't see it in this list of dependencies (or which versions of `g++` will work for compiling `gt_pro mk_pool db_val db_dump db_uniq db_build`

**Comment by nick-youngblut** [comment]
It would also be helpful to list the dependency version for https://github.com/zjshi/gt-pro#additional-dependencies

**Comment by zjshi** [comment]
Thanks Nick! I have added the dependency versions to the documentation in this repo. We have also published a protocol to provide a step-by-step tutorial for customized database building using Maast and GT-Pro. Please see this link for details (https://www.sciencedirect.com/science/article/pii/S2666166722008449)

**Comment by nick-youngblut** [comment]
> I have added the dependency versions to the documentation in this repo.
Thanks @zjshi! ...and thanks for the link to the step-by-step tutorial. Is the protocol manuscript linked in the GT-Pro readme or tutorial? I don't see it in either doc.

**Comment by zjshi** [comment]
It was not there until my update last week, again apologies... Here is what it looks like now
![image](https://github.com/zjshi/gt-pro/assets/23440370/5c032ca7-4009-4be1-aefb-a8a14f1a4e6f)
