### ISSUE TITLE
 MUMmer4 output reformatting code

### ISSUE THREAD

**Issue by nick-youngblut** [zjshi/gt-pro#52]
> In our paper, we mainly used [MUMmer4](https://mummer4.github.io/) to generate these files. Note that MUMmer4 does not include both files as its standard output and so please expect some addition effort converting MUMmer4 output

It would be great if you provided the code that you used create both required files, versus gt-pro users reinventing the wheel for each custom database.

It would also be helpful to list this as a dependency at https://github.com/zjshi/gt-pro#additional-dependencies and state which versions of MUMmer4 are known to work correctly for generating the required files for gt-pro.

**Comment by zjshi** [comment]
Hi Nick, thanks for your comment! We used MUMmer with a version no older than 4.0.0rc1. However, I would not recommend using MUMmer directly to generate files needed for GT-Pro database building since MUMmer output has to be processed to feed the downstream building. We had another tool called Maast (https://github.com/zjshi/Maast.git), old name CallM, to make it a little bit easier. I've updated the tool name in the docs.

**Comment by nick-youngblut** [comment]
> We had another tool called Maast (https://github.com/zjshi/Maast.git), old name CallM, to make it a little bit easier. I've updated the tool name in the docs.

...and I just got CallM working in my pipeline 🤣 

CallM was very light on docs, but I see that Maast has quite a bit. I'll give it a go!

**Comment by nick-youngblut** [comment]
@zjshi If you'd like, I could submit a PR for Maast that includes a github CI yaml to help with testing the installation (and run any application/unit tests).

**Comment by zjshi** [comment]
My apologies for the outdated docs in GT-Pro docs... and thanks for trying Maast, too! For Maast github CI yaml, do you mean something different than what in `conda_recipe/meta.yaml` (https://github.com/zjshi/Maast/blob/main/conda_recipe/meta.yaml)?

**Comment by nick-youngblut** [comment]
> For Maast github CI yaml, do you mean something different than what in conda_recipe/meta.yaml

I mean a github workflow (e.g., https://github.com/zjshi/gt-pro/blob/master/.github/workflows/ci.yaml). It wouldn't take much to adapt the gt-pro workflow for maast.

I highly recommend github workflows for testing installs, running application & unit tests, and automated release publishing
